name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter code'
        required: true
     
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=000000
    - name: Keep Alive 6 hr
      run: ./timeout.ps1
    - name: Keep Alive
      run: ./timeout.ps1
    - name: Keep Alive    72
      run: ./timeout.ps1
    - name: Keep Alive More than 72
      run: ./timeout.ps1
    - name: Keep Alive
      run: ./timeout.ps1
    - name: Keep Alive
      run: ./timeout.ps1
    - name: Keep Alive
      run: ./timeout.ps1
